MASSEUSE_CATALOG = [
    {
        'slug': 'julia',
        'name': 'Julia',
        'surname': '',
        'exp_years': 8,
        'order': 1,
        'spec_cs': 'Klasická & Relax masáž',
        'spec_en': 'Classic & Relax Massage',
        'spec_ru': 'Классический & Релакс-массаж',
        'service_slugs': ['klasicka-masaz', 'cbd-relaxacni-masaz', 'thajska-masaz'],
    },
    {
        'slug': 'diana',
        'name': 'Diana',
        'surname': '',
        'exp_years': 5,
        'order': 2,
        'spec_cs': 'Uvolňující & Aromamasáž',
        'spec_en': 'Relaxing & Aroma Massage',
        'spec_ru': 'Расслабляющий & Аромамассаж',
        'service_slugs': ['thajska-masaz', 'aromaterapie', 'cbd-relaxacni-masaz'],
    },
    {
        'slug': 'laura',
        'name': 'Laura',
        'surname': '',
        'exp_years': 6,
        'order': 3,
        'spec_cs': 'Aromamasáž & Relax masáž',
        'spec_en': 'Aroma & Relax Massage',
        'spec_ru': 'Аромамассаж & Релакс-массаж',
        'service_slugs': ['aromaterapie', 'cbd-relaxacni-masaz', 'klasicka-masaz'],
    },
    {
        'slug': 'vanessa',
        'name': 'Vanessa',
        'surname': '',
        'exp_years': 10,
        'order': 4,
        'spec_cs': 'Klasická & Sportovní masáž',
        'spec_en': 'Classic & Sports Massage',
        'spec_ru': 'Классический & Спортивный массаж',
        'service_slugs': ['klasicka-masaz', 'sportovni-masaz', 'lymfaticka-masaz'],
    },
    {
        'slug': 'ella',
        'name': 'Ella',
        'surname': '',
        'exp_years': 7,
        'order': 5,
        'spec_cs': 'Sportovní & Regenerační masáž',
        'spec_en': 'Sports & Recovery Massage',
        'spec_ru': 'Спортивный & Восстановительный массаж',
        'service_slugs': ['sportovni-masaz', 'klasicka-masaz', 'thajska-masaz'],
    },
    {
        'slug': 'mira',
        'name': 'Mira',
        'surname': '',
        'exp_years': 4,
        'order': 6,
        'spec_cs': 'Lymfatická & Aromamasáž',
        'spec_en': 'Lymphatic & Aroma Massage',
        'spec_ru': 'Лимфодренажный & Аромамассаж',
        'service_slugs': ['lymfaticka-masaz', 'aromaterapie', 'cbd-relaxacni-masaz'],
    },
]
