SERVICE_CATALOG = [
    {
        'slug': 'vip-masaz',
        'name_cs': 'VIP masáž',
        'name_en': 'VIP Massage',
        'name_ru': 'VIP-массаж',
        'duration_minutes': 60,
        'base_price': 2500,
        'order': 1,
        'keyword_cs': 'VIP masáž',
        'keyword_en': 'VIP massage',
        'keyword_ru': 'VIP-массаж',
        'technique_cs': 'jemné a hluboké techniky s prémiálními oleji',
        'technique_en': 'gentle and deep techniques with premium oils',
        'technique_ru': 'мягкие и глубокие техники с премиальными маслами',
        'benefit_cs': 'celkové uvolnění, luxusní zážitek a obnovu energie',
        'benefit_en': 'full relaxation, a luxurious experience and energy renewal',
        'benefit_ru': 'полное расслабление, роскошный опыт и восстановление энергии',
        'audience_cs': 'klienty hledající prémiový zážitek a hlubokou relaxaci',
        'audience_en': 'clients seeking a premium experience and deep relaxation',
        'audience_ru': 'клиентов, ищущих премиальный опыт и глубокое расслабление',
    },
    {
        'slug': 'relaxacni-masaz',
        'name_cs': 'Relaxační masáž',
        'name_en': 'Relaxation Massage',
        'name_ru': 'Расслабляющий массаж',
        'duration_minutes': 60,
        'base_price': 2000,
        'order': 2,
        'keyword_cs': 'relaxační masáž',
        'keyword_en': 'relaxation massage',
        'keyword_ru': 'расслабляющий массаж',
        'technique_cs': 'jemné hladivé hmaty s teplými oleji',
        'technique_en': 'gentle gliding strokes with warm oils',
        'technique_ru': 'мягкие поглаживающие движения с тёплыми маслами',
        'benefit_cs': 'hlubokou relaxaci, uvolnění stresu a celkovou pohodu',
        'benefit_en': 'deep relaxation, stress relief and overall wellbeing',
        'benefit_ru': 'глубокую релаксацию, снятие стресса и общее благополучие',
        'audience_cs': 'každého, kdo hledá uvolnění a odpočinek',
        'audience_en': 'anyone seeking relief and rest',
        'audience_ru': 'всех, кто ищет расслабление и отдых',
    },
    {
        'slug': 'masaz-pro-zeny',
        'name_cs': 'Masáž pro ženy',
        'name_en': 'Massage for Women',
        'name_ru': 'Массаж для женщин',
        'duration_minutes': 60,
        'base_price': 4000,
        'order': 3,
        'keyword_cs': 'masáž pro ženy',
        'keyword_en': 'massage for women',
        'keyword_ru': 'массаж для женщин',
        'technique_cs': 'speciální ženské techniky kombinující jemnost a hloubku',
        'technique_en': 'special feminine techniques combining gentleness and depth',
        'technique_ru': 'особые женские техники, сочетающие нежность и глубину',
        'benefit_cs': 'harmonizaci těla, hormonální rovnováhu a pocit péče',
        'benefit_en': 'body harmony, hormonal balance and a feeling of care',
        'benefit_ru': 'гармонизацию тела, гормональный баланс и ощущение заботы',
        'audience_cs': 'ženy všech věkových kategorií hledající péči těla i duše',
        'audience_en': 'women of all ages seeking body and mind care',
        'audience_ru': 'женщин всех возрастов, ищущих заботу о теле и душе',
    },
    {
        'slug': 'masaz-pro-pary',
        'name_cs': 'Masáž pro páry',
        'name_en': 'Couples Massage',
        'name_ru': 'Массаж для пар',
        'duration_minutes': 60,
        'base_price': 1900,
        'order': 4,
        'keyword_cs': 'masáž pro páry',
        'keyword_en': 'couples massage',
        'keyword_ru': 'массаж для пар',
        'technique_cs': 'synchronizované hmaty dvou masérek ve společném pokoji',
        'technique_en': 'synchronised strokes by two masseuses in a shared room',
        'technique_ru': 'синхронизированные движения двух массажисток в одном кабинете',
        'benefit_cs': 'sdílený luxusní zážitek, posílení vztahu a hlubokou relaxaci',
        'benefit_en': 'a shared luxury experience, relationship strengthening and deep relaxation',
        'benefit_ru': 'совместный роскошный опыт, укрепление отношений и глубокую релаксацию',
        'audience_cs': 'páry hledající romantický a luxusní společný zážitek',
        'audience_en': 'couples seeking a romantic and luxurious shared experience',
        'audience_ru': 'пары, ищущие романтический и роскошный совместный опыт',
    },
]
