SERVICE_CATALOG = [
    {
        'slug': 'klasicka-masaz',
        'name_cs': 'Klasická masáž',
        'name_en': 'Classic Massage',
        'name_ru': 'Классический массаж',
        'duration_minutes': 60,
        'base_price': 1900,
        'order': 1,
        'keyword_cs': 'klasická masáž',
        'keyword_en': 'classic massage',
        'keyword_ru': 'классический массаж',
        'technique_cs': 'švédské hmaty, hladění a hnětání',
        'technique_en': 'Swedish strokes, gliding and kneading',
        'technique_ru': 'шведские движения, поглаживание и разминание',
        'benefit_cs': 'uvolnění svalového napětí, lepší spánek a regenerace',
        'benefit_en': 'muscle tension relief, better sleep and recovery',
        'benefit_ru': 'снятие мышечного напряжения, улучшение сна и восстановление',
        'audience_cs': 'začátečníky i klienty se stresovým napětím zad a krku',
        'audience_en': 'beginners and clients with stress-related neck and back tension',
        'audience_ru': 'начинающих и клиентов со стрессовым напряжением спины и шеи',
    },
    {
        'slug': 'cbd-relaxacni-masaz',
        'name_cs': 'Hlubokotkanivní masáž',
        'name_en': 'Deep Tissue Massage',
        'name_ru': 'Глубокотканный массаж',
        'duration_minutes': 60,
        'base_price': 2500,
        'order': 2,
        'keyword_cs': 'hlubokotkanivní masáž',
        'keyword_en': 'deep tissue massage',
        'keyword_ru': 'глубокотканный массаж',
        'technique_cs': 'pomalé pevné hmaty zaměřené na hluboké svalové vrstvy a spouštěcí body',
        'technique_en': 'slow firm strokes focused on deep muscle layers and trigger points',
        'technique_ru': 'медленные уверенные движения, направленные на глубокие мышечные слои и триггерные точки',
        'benefit_cs': 'uvolnění chronického napětí, flexibilitu svalů a regeneraci',
        'benefit_en': 'release of chronic tension, muscle flexibility and recovery',
        'benefit_ru': 'снятие хронического напряжения, гибкость мышц и восстановление',
        'audience_cs': 'klienty se chronickým napětím svalů zad, krku nebo ramen',
        'audience_en': 'clients with chronic muscle tension in the back, neck or shoulders',
        'audience_ru': 'клиентов с хроническим напряжением мышц спины, шеи или плеч',
    },
    {
        'slug': 'thajska-masaz',
        'name_cs': 'Uvolňující masáž',
        'name_en': 'Relaxing Massage',
        'name_ru': 'Расслабляющий массаж',
        'duration_minutes': 60,
        'base_price': 2000,
        'order': 3,
        'keyword_cs': 'uvolňující masáž',
        'keyword_en': 'relaxing massage',
        'keyword_ru': 'расслабляющий массаж',
        'technique_cs': 'jemné hmaty, hluboké uvolnění a harmonizaci těla',
        'technique_en': 'gentle strokes, deep release and body harmonisation',
        'technique_ru': 'мягкие движения, глубокое расслабление и гармонизацию тела',
        'benefit_cs': 'hlubokou relaxaci, energii a pocit lehkosti',
        'benefit_en': 'deep relaxation, renewed energy and a feeling of lightness',
        'benefit_ru': 'глубокую релаксацию, энергию и чувство легкости',
        'audience_cs': 'klienty hledající klid a regeneraci po náročném dni',
        'audience_en': 'clients seeking calm and recovery after a demanding day',
        'audience_ru': 'клиентов, которые ищут покой и восстановление после напряжённого дня',
    },
    {
        'slug': 'sportovni-masaz',
        'name_cs': 'Sportovní masáž',
        'name_en': 'Sports Massage',
        'name_ru': 'Спортивный массаж',
        'duration_minutes': 60,
        'base_price': 2500,
        'order': 4,
        'keyword_cs': 'sportovní masáž',
        'keyword_en': 'sports massage',
        'keyword_ru': 'спортивный массаж',
        'technique_cs': 'hlubší tlakové techniky zaměřené na svalové skupiny',
        'technique_en': 'deeper pressure techniques focused on muscle groups',
        'technique_ru': 'более глубокие техники давления, направленные на мышечные группы',
        'benefit_cs': 'regeneraci po tréninku a prevenci zranění',
        'benefit_en': 'post-workout recovery and injury prevention',
        'benefit_ru': 'восстановление после тренировок и предотвращение травм',
        'audience_cs': 'sportovce a aktivní jedince',
        'audience_en': 'athletes and active individuals',
        'audience_ru': 'спортсменов и активных людей',
    },
    {
        'slug': 'lymfaticka-masaz',
        'name_cs': 'Lymfatická masáž',
        'name_en': 'Lymphatic Massage',
        'name_ru': 'Лимфодренажный массаж',
        'duration_minutes': 60,
        'base_price': 3300,
        'order': 5,
        'keyword_cs': 'lymfatická masáž',
        'keyword_en': 'lymphatic massage',
        'keyword_ru': 'лимфодренажный массаж',
        'technique_cs': 'jemné rytmické hmaty podporující lymfatický systém',
        'technique_en': 'gentle rhythmic strokes supporting the lymphatic system',
        'technique_ru': 'мягкие ритмичные движения для поддержки лимфатической системы',
        'benefit_cs': 'detoxikaci, redukci otoků a pocit lehkosti',
        'benefit_en': 'detoxification, reduced swelling and a feeling of lightness',
        'benefit_ru': 'детоксикацию, уменьшение отёков и чувство легкости',
        'audience_cs': 'klienty s pocitem těžkosti nohou nebo po dlouhém cestování',
        'audience_en': 'clients with heavy legs or after long travel',
        'audience_ru': 'клиентов с тяжестью в ногах или после длительных поездок',
    },
    {
        'slug': 'aromaterapie',
        'name_cs': 'Aromamasáž',
        'name_en': 'Aroma Massage',
        'name_ru': 'Аромамассаж',
        'duration_minutes': 60,
        'base_price': 2200,
        'order': 6,
        'keyword_cs': 'aromamasáž',
        'keyword_en': 'aroma massage',
        'keyword_ru': 'аромамассаж',
        'technique_cs': 'jemné hmaty s prémiovými éterickými oleji',
        'technique_en': 'gentle strokes with premium essential oils',
        'technique_ru': 'мягкие движения с премиальными эфирными маслами',
        'benefit_cs': 'hlubokou relaxaci, harmonii nervového systému a lepší spánek',
        'benefit_en': 'deep relaxation, nervous system balance and better sleep',
        'benefit_ru': 'глубокую релаксацию, гармонию нервной системы и лучший сон',
        'audience_cs': 'klienty se stresem, úzkostí nebo nespavostí',
        'audience_en': 'clients with stress, anxiety or sleep issues',
        'audience_ru': 'клиентов со стрессом, тревогой или проблемами со сном',
    },
]
