# Generated by Django 5.1.1 on 2026-06-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MassageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name_cs', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('description_cs', models.TextField()),
                ('description_en', models.TextField()),
                ('description_ru', models.TextField()),
                ('duration_minutes', models.IntegerField()),
                ('base_price', models.IntegerField()),
                ('meta_title', models.CharField(default='', max_length=60)),
                ('meta_description', models.CharField(default='', max_length=160)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Massage Types',
                'ordering': ['order'],
            },
        ),
    ]
