# Generated by Django 4.2.30 on 2026-06-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_massagetype_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='massagetype',
            options={'ordering': ['order'], 'verbose_name': 'Massage type', 'verbose_name_plural': 'Massage types'},
        ),
        migrations.AlterField(
            model_name='massagetype',
            name='base_price',
            field=models.IntegerField(verbose_name='Base price'),
        ),
        migrations.AlterField(
            model_name='massagetype',
            name='description_cs',
            field=models.TextField(verbose_name='Description (CS)'),
        ),
        migrations.AlterField(
            model_name='massagetype',
            name='description_en',
            field=models.TextField(verbose_name='Description (EN)'),
        ),
        migrations.AlterField(
            model_name='massagetype',
            name='description_ru',
            field=models.TextField(verbose_name='Description (RU)'),
        ),
        migrations.AlterField(
            model_name='massagetype',
            name='duration_minutes',
            field=models.IntegerField(verbose_name='Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='massagetype',
            name='image',
            field=models.ImageField(blank=True, upload_to='services/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='massagetype',
            name='image_alt',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Image alt'),
        ),
        migrations.AlterField(
            model_name='massagetype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='massagetype',
            name='meta_description',
            field=models.CharField(default='', max_length=160, verbose_name='Meta description'),
        ),
        migrations.AlterField(
            model_name='massagetype',
            name='meta_title',
            field=models.CharField(default='', max_length=60, verbose_name='Meta title'),
        ),
        migrations.AlterField(
            model_name='massagetype',
            name='name_cs',
            field=models.CharField(max_length=100, verbose_name='Name (CS)'),
        ),
        migrations.AlterField(
            model_name='massagetype',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Name (EN)'),
        ),
        migrations.AlterField(
            model_name='massagetype',
            name='name_ru',
            field=models.CharField(max_length=100, verbose_name='Name (RU)'),
        ),
        migrations.AlterField(
            model_name='massagetype',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='massagetype',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
