# Generated by Django 5.1.1 on 2026-06-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title_cs', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ru', models.CharField(max_length=200)),
                ('excerpt_cs', models.CharField(default='', max_length=500)),
                ('excerpt_en', models.CharField(default='', max_length=500)),
                ('excerpt_ru', models.CharField(default='', max_length=500)),
                ('content_cs', models.TextField()),
                ('content_en', models.TextField()),
                ('content_ru', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='blog/')),
                ('image_alt', models.CharField(default='', max_length=200)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
