from django.core.management.base import BaseCommand
from apps.blog.models import Post

class Command(BaseCommand):
    help = 'Create initial 3 blog posts for SEO'

    def handle(self, *args, **options):
        posts_data = [
            {
                'slug': 'koristi-masazu-pro-zdorovi',
                'title_cs': 'Přínosy masáže pro zdraví a pohodu',
                'title_en': 'Health Benefits of Massage Therapy',
                'title_ru': 'Пользу массажа для здоровья',
                'excerpt_cs': 'Masáž je jedním z nejúčinnějších způsobů, jak se postarat o své fyzické a duševní zdraví. Objevte, jak profesionální masáž může zlepšit kvalitu vašeho života.',
                'excerpt_en': 'Massage is one of the most effective ways to take care of your physical and mental health. Discover how professional massage can improve your quality of life.',
                'excerpt_ru': 'Массаж - это один из самых эффективных способов заботиться о своем физическом и психическом здоровье. Откройте для себя, как профессиональный массаж может улучшить качество вашей жизни.',
                'content_cs': 'Masáž je starověká umělecká a vědecká disciplína, která si po tisíce let drží své místo jako základní složka zdravotnictví a wellness. V našem moderním, hektickém světě, kde se stres stal nedílnou součástí našich životů, se masáž stala více než kdy dříve nezbytnou součástí péče o sebe.\n\n## Fyzické přínosy masáže\n\nProfesionální masáž má několik ověřených fyzických přínosů. V první řadě pomáhá uvolnit napjaté svaly a zlepšuje jejich flexibilitu. Když naše svaly trpí stresem a tenzí, dochází k jejich ztuhlosti a bolesti. Masáž pomáhá rozpustit tyto bloky a obnovuje přirozený pohyb těla.\n\nZa druhé, masáž výrazně zlepšuje krevní oběh. Zvýšený průtok krve přináší více kyslíku a živin do tkání a odstraňuje toxiny a odpadní látky. To podporuje regeneraci těla a urychluje hojení poranění.\n\n## Duševní a emoční přínosy\n\nVedle fyzických přínosů má masáž hluboký dopad na naši duševní pohodu. Během masáže se naše tělo uvolňuje a do krve se dostává více endorfinů - těch chemických látek, které vyvolávají pocit klidu a pohody. Mnoho klientů hlásí, že se po masáži cítí omlazeni a osvěženi, jako by se zbavili břemena, které na nich leželo.\n\n## Regulace kortizolu\n\nKortizol je hormon stresu. Chronicky zvýšené hladiny kortizolu mohou vést k řadě zdravotních problémů včetně zhoršené imunity, poruch spánku a psychických problémů. Vědecké studie prokázaly, že pravidelná masáž výrazně snižuje hladiny kortizolu, čímž pomáhá tělu vrátit se do rovnováhy.\n\n## Zlepšení spánku\n\nPokud trpíte nespavostí, masáž by se měla stát součástí vaší relaxační rutiny. Uvolnění svalů, snížení stresu a zvýšení endorfinů všechny přispívají k hlubšímu a kvalitativnějšímu spánku.\n\n## Posílení imunity\n\nPřekvinvě, ale masáž také posiluje imunitní systém. Studium z roku 2010 prokázalo, že masáž zvyšuje počet bílých krvinek, které jsou klíčové pro boj proti infekcím a nemocem.\n\n## Masáž v Black Elixir Spa\n\nV Black Elixir Spa si osvojujeme staré tradice a kombinujeme je s moderními technikami. Naše zkušené masérky jsou školeny v různých stylech masáže - od klasické evropské masáže po asijské techniky jako je thajská masáž a aromaterapie.\n\nAť již hledáte linii pro uvolnění napjaté krční páteře, léčbu sportovních zranění nebo prostě jen relaxaci, máme masáž, která je pro vás ideální.\n\n## Závěr\n\nInvestování do pravidelné masáže je investicí do vaší budoucnosti. Není to jen luxus, ale nezbytná součást zdravého životního stylu. Pokud jste s masáží dosud neměli zkušenost, či pokud jste ji dlouho neměli, pozveme vás, abyste si jí znovu dopřáli. Vaše tělo i mysl vám za to budou vděčny.',
                'content_en': 'Massage is an ancient art and science that has maintained its place as a fundamental component of healthcare and wellness for thousands of years. In our modern, hectic world, where stress has become an integral part of our lives, massage has become more essential than ever before.\n\n## Physical Benefits of Massage\n\nProfessional massage has several proven physical benefits. First and foremost, it helps release tense muscles and improves their flexibility. When our muscles suffer from stress and tension, they become stiff and painful. Massage helps dissolve these blocks and restores the body\'s natural movement.\n\nSecondly, massage significantly improves blood circulation. Increased blood flow brings more oxygen and nutrients to tissues and removes toxins and waste products. This supports body regeneration and accelerates wound healing.\n\n## Mental and Emotional Benefits\n\nBeyond physical benefits, massage has a profound impact on our mental well-being. During massage, our body relaxes and endorphins enter the bloodstream—those chemical substances that evoke feelings of calm and wellbeing. Many clients report feeling rejuvenated and refreshed after a massage, as if they have shed a burden that was weighing them down.\n\n## Cortisol Regulation\n\nCortisol is the stress hormone. Chronically elevated cortisol levels can lead to a range of health problems including weakened immunity, sleep disturbances, and mental health issues. Scientific studies have shown that regular massage significantly reduces cortisol levels, helping the body return to balance.\n\n## Improved Sleep\n\nIf you suffer from insomnia, massage should become part of your relaxation routine. Muscle relaxation, stress reduction, and increased endorphins all contribute to deeper and higher-quality sleep.\n\n## Immune System Boost\n\nSurprisingly, massage also strengthens the immune system. A 2010 study showed that massage increases white blood cell count, which are crucial for fighting infections and diseases.\n\n## Massage at Black Elixir Spa\n\nAt Black Elixir Spa, we embrace old traditions and combine them with modern techniques. Our experienced therapists are trained in various massage styles—from classic European massage to Asian techniques such as Thai massage and aromatherapy.\n\nWhether you\'re looking for relief from a tense neck, treatment for sports injuries, or simply relaxation, we have a massage that is ideal for you.\n\n## Conclusion\n\nInvesting in regular massage is investing in your future. It\'s not just a luxury, but an essential part of a healthy lifestyle. If you haven\'t experienced massage before, or if it\'s been a while, we invite you to indulge in it again. Your body and mind will thank you for it.',
                'content_ru': 'Массаж - это древнее искусство и наука, которые тысячелетиями остаются фундаментальной составляющей здравоохранения и оздоровления. В нашем современном, насыщенном мире, где стресс стал неотъемлемой частью нашей жизни, массаж стал более необходимым, чем когда-либо.\n\n## Физические преимущества массажа\n\nПрофессиональный массаж имеет ряд доказанных физических преимуществ. В первую очередь, он помогает расслабить напряженные мышцы и улучшить их гибкость. Когда наши мышцы страдают от стресса и напряжения, они становятся жесткими и болезненными. Массаж помогает растворить эти блоки и восстановить естественное движение тела.\n\nВо-вторых, массаж значительно улучшает кровообращение. Повышенный кровоток приносит больше кислорода и питательных веществ в ткани и удаляет токсины и отходы. Это поддерживает регенерацию тела и ускоряет заживление ран.\n\n## Психические и эмоциональные преимущества\n\nПомимо физических преимуществ, массаж оказывает глубокое влияние на наше психическое благополучие. Во время массажа наше тело расслабляется, и в кровь попадают эндорфины - химические вещества, которые вызывают чувства спокойствия и гармонии. Многие клиенты сообщают, что после массажа чувствуют себя омоложенными и освеженными, как будто они сбросили груз, который на них лежал.'
            },
            {
                'slug': 'relaks-meditace-masaz',
                'title_cs': 'Relaxace a meditace: Jak masáž pomáhá najít vnitřní pokoj',
                'title_en': 'Relaxation and Meditation: How Massage Helps Find Inner Peace',
                'title_ru': 'Релаксация и медитация: как массаж помогает найти внутренний мир',
                'excerpt_cs': 'Spojení masáže s mediativními technikami vytváří silný synergický efekt. Naučte se, jak dosáhnout hlubokého vnitřního pokoje a rovnováhy pomocí komplexního wellness přístupu.',
                'excerpt_en': 'The combination of massage with meditative techniques creates a powerful synergistic effect. Learn how to achieve deep inner peace and balance through a comprehensive wellness approach.',
                'excerpt_ru': 'Комбинация массажа с медитативными техниками создает мощный синергетический эффект. Узнайте, как достичь глубокого внутреннего мира и равновесия благодаря комплексному подходу к благополучию.',
                'content_cs': 'V dnešní hektické společnosti se snažíme najít chvíle klidu a vnitřního pokoje. Masáž v kombinaci s meditativními praktikami představuje jednu z nejúčinnějších cest k dosažení této rovnováhy.\n\n## Vědomí a přítomnost\n\nMeditace je starobylá praxe, která nám pomáhá stát se si vědomi přítomného okamžiku a usnadňuje nám vidět věci bez odsudku. Kombinujete-li tuto vědomost s hlubokým fyzickým uvolněním, které přináší masáž, vytváříte ideální prostředí pro transformaci.\n\n## Hluboka relaxace těla\n\nBěhem masáže se vaše tělo postupně uvolňuje, napětí se rozpouští a svalová pamět se "resetuje". Tímto procesem se vaše mysl také přirozeně usadí.\n\n## Aktivace parasympatického nervového systému\n\nNáš autonomní nervový systém má dvě hlavní režimy: sympatický (boj nebo útěk) a parasympatický (odpočinek a regenerace). V moderní společnosti jsme často v sympatickém režimu. Masáž a meditace nás přesouvají do parasympatického režimu, kde se opravdu uzdravujeme.',
                'content_en': 'In today\'s hectic society, we strive to find moments of peace and inner tranquility. Massage combined with meditative practices represents one of the most effective paths to achieving this balance.\n\n## Awareness and Presence\n\nMeditation is an ancient practice that helps us become aware of the present moment and enables us to see things without judgment. When you combine this awareness with the deep physical relaxation that massage provides, you create an ideal environment for transformation.\n\n## Deep Body Relaxation\n\nDuring a massage, your body gradually relaxes, tension dissolves, and muscle memory is "reset." Through this process, your mind naturally settles as well.\n\n## Activation of the Parasympathetic Nervous System\n\nOur autonomic nervous system has two main modes: sympathetic (fight or flight) and parasympathetic (rest and recovery). In modern society, we\'re often in sympathetic mode. Massage and meditation shift us into parasympathetic mode, where true healing occurs.',
                'content_ru': 'В современном хаотичном обществе мы пытаемся найти моменты мира и внутренней гармонии. Массаж в сочетании с медитативными практиками представляет собой один из самых эффективных путей достижения этого баланса.\n\n## Осознанность и присутствие\n\nМедитация - это древняя практика, которая помогает нам осознать настоящий момент и позволяет видеть вещи без суждения. Когда вы сочетаете эту осознанность с глубокой физической релаксацией, которую обеспечивает массаж, вы создаете идеальную среду для трансформации.\n\n## Глубокая релаксация тела\n\nВо время массажа ваше тело постепенно расслабляется, напряжение растворяется, и мышечная память "перезагружается". Благодаря этому процессу ваш ум естественно успокаивается.'
            },
            {
                'slug': 'spa-retreat-kompletni-pruvodce',
                'title_cs': 'Wellness Retreat: Kompletní průvodce regeneračním víkendem',
                'title_en': 'Wellness Retreat: Complete Guide to a Restorative Weekend',
                'title_ru': 'Спа-ретрит: полное руководство к восстановительному выходному',
                'excerpt_cs': 'Plánujete si wellness víkend? Naučte se, jak si maximálně užít spa ošetření, včetně tipů pro přípravu, výběr správných procedur a péče po masáži.',
                'excerpt_en': 'Planning a wellness weekend? Learn how to maximize your spa experience, including preparation tips, choosing the right treatments, and post-massage care.',
                'excerpt_ru': 'Планируете спа-выходные? Узнайте, как максимально насладиться спа-процедурами, включая советы по подготовке, выбору правильных процедур и уходу после массажа.',
                'content_cs': 'Spa víkend nebo wellness RetReat není luxus, ale investice do vašeho zdraví a pohody. V tomto průvodci vám ukážeme, jak si zprostředkovat nejen nejlepší massage, ale celou transformační zkušenost.\n\n## Příprava na spa víkend\n\nVíkend do spa by měl začít několik dní předem.\n\n## Výběr správných procedur\n\nV Black Elixir Spa nabízíme různé typy masáží.\n\n## Během masáže\n\nBěhem samotné masáže se snažte zcela se uvolnit a komunikujte s terapeautem.\n\n## Po masáži - péče a regenerace\n\nPéče po masáži je stejně důležitá jako sama masáž. Dejte si čas na odpočinek a hydrataci.\n\n## Speciální balíčky pro víkend\n\nNabízíme speciální balíčky pro wellness víkendy včetně Couples Retreat a Solo Retreat.\n\n## Závěr\n\nWellness víkend je výjimečná příležitost, jak se vrátit k sobě a znovu se připojit se svým tělem.',
                'content_en': 'A spa weekend or wellness retreat is not a luxury, but an investment in your health and well-being. In this guide, we\'ll show you how to experience not just the best massage, but an entire transformational experience.\n\n## Preparing for a Spa Weekend\n\nA spa weekend should begin several days in advance. Start drinking more water and prefer lighter food.\n\n## Choosing the Right Treatments\n\nAt Black Elixir Spa, we offer various types of massages including classic, Thai, and aromatherapy.\n\n## During the Massage\n\nDuring the massage itself, try to fully relax and communicate with your therapist.\n\n## After Massage - Care and Recovery\n\nPost-massage care is as important as the massage itself. Rest and hydrate properly.\n\n## Special Packages for the Weekend\n\nWe offer special packages for wellness weekends including Couples Retreat and Solo Retreat.\n\n## Conclusion\n\nA wellness weekend is an exceptional opportunity to return to yourself and reconnect with your body.',
                'content_ru': 'Спа-выходные или wellness-ретрит - это не роскошь, а инвестирование в ваше здоровье и благополучие. В этом руководстве мы покажем вам, как испытать не просто лучший массаж, но целостный трансформационный опыт.\n\n## Подготовка к спа-выходным\n\nСпа-выходные должны начинаться несколько дней назад. Начните пить больше воды и отдавайте предпочтение легкой пище.\n\n## Выбор правильных процедур\n\nВ Black Elixir Spa мы предлагаем различные виды массажа.\n\n## Во время массажа\n\nВо время самого массажа старайтесь полностью расслабиться.\n\n## После массажа\n\nУход после массажа очень важен. Отдохните и гидратируйтесь.\n\n## Специальные пакеты\n\nМы предлагаем специальные пакеты для спа-выходных.\n\n## Заключение\n\nСпа-выходной - это исключительная возможность вернуться к себе.'
            }
        ]

        for post_data in posts_data:
            post, created = Post.objects.update_or_create(
                slug=post_data['slug'],
                defaults={
                    'title_cs': post_data['title_cs'],
                    'title_en': post_data['title_en'],
                    'title_ru': post_data['title_ru'],
                    'excerpt_cs': post_data['excerpt_cs'],
                    'excerpt_en': post_data['excerpt_en'],
                    'excerpt_ru': post_data['excerpt_ru'],
                    'content_cs': post_data['content_cs'],
                    'content_en': post_data['content_en'],
                    'content_ru': post_data['content_ru'],
                    'is_published': True,
                }
            )
            status = "Created" if created else "Updated"
            self.stdout.write(self.style.SUCCESS(f'{status} post: {post.title_cs}'))
