# Generated by Django 5.1.1 on 2026-06-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masseuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('bio_cs', models.TextField()),
                ('bio_en', models.TextField()),
                ('bio_ru', models.TextField()),
                ('spec_cs', models.CharField(max_length=200)),
                ('spec_en', models.CharField(max_length=200)),
                ('spec_ru', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='masseuses/')),
                ('photo_alt', models.CharField(max_length=200)),
                ('meta_title', models.CharField(default='', max_length=60)),
                ('meta_description', models.CharField(default='', max_length=160)),
                ('exp_years', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('services', models.ManyToManyField(to='services.massagetype')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
