# Generated by Django 5.1.1 on 2026-06-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masseurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masseuse',
            name='photo',
            field=models.ImageField(blank=True, upload_to='masseuses/'),
        ),
    ]
