# Generated by Django 4.2.30 on 2026-06-16 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_work_location_and_shift'),
        ('media_library', '0001_initial'),
        ('masseurs', '0003_masseuse_cloudinary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masseuse',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Masseuse', 'verbose_name_plural': 'Masseuses'},
        ),
        migrations.AlterField(
            model_name='masseuse',
            name='bio_cs',
            field=models.TextField(verbose_name='Bio (CS)'),
        ),
        migrations.AlterField(
            model_name='masseuse',
            name='bio_en',
            field=models.TextField(verbose_name='Bio (EN)'),
        ),
        migrations.AlterField(
            model_name='masseuse',
            name='bio_ru',
            field=models.TextField(verbose_name='Bio (RU)'),
        ),
        migrations.AlterField(
            model_name='masseuse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='masseuse',
            name='exp_years',
            field=models.IntegerField(default=0, verbose_name='Years of experience'),
        ),
        migrations.AlterField(
            model_name='masseuse',
            name='gallery_cloudinary',
            field=models.ManyToManyField(blank=True, related_name='masseuse_gallery', to='media_library.cloudinaryimage', verbose_name='Gallery (Cloudinary)'),
        ),
        migrations.AlterField(
            model_name='masseuse',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='masseuse',
            name='main_cloudinary_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masseuse_main', to='media_library.cloudinaryimage', verbose_name='Main photo (Cloudinary)'),
        ),
        migrations.AlterField(
            model_name='masseuse',
            name='meta_description',
            field=models.CharField(default='', max_length=160, verbose_name='Meta description'),
        ),
        migrations.AlterField(
            model_name='masseuse',
            name='meta_title',
            field=models.CharField(default='', max_length=60, verbose_name='Meta title'),
        ),
        migrations.AlterField(
            model_name='masseuse',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='masseuse',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='masseuse',
            name='photo',
            field=models.ImageField(blank=True, upload_to='masseuses/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='masseuse',
            name='photo_alt',
            field=models.CharField(max_length=200, verbose_name='Photo alt'),
        ),
        migrations.AlterField(
            model_name='masseuse',
            name='services',
            field=models.ManyToManyField(to='services.massagetype', verbose_name='Services'),
        ),
        migrations.AlterField(
            model_name='masseuse',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='masseuse',
            name='spec_cs',
            field=models.CharField(max_length=200, verbose_name='Specialization (CS)'),
        ),
        migrations.AlterField(
            model_name='masseuse',
            name='spec_en',
            field=models.CharField(max_length=200, verbose_name='Specialization (EN)'),
        ),
        migrations.AlterField(
            model_name='masseuse',
            name='spec_ru',
            field=models.CharField(max_length=200, verbose_name='Specialization (RU)'),
        ),
        migrations.AlterField(
            model_name='masseuse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
