# Generated by Django 5.1.1 on 2026-06-11 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masseurs', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True)),
                ('is_booked', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('masseuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='masseurs.masseuse')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.massagetype')),
            ],
            options={
                'ordering': ['start_time'],
                'unique_together': {('masseuse', 'start_time', 'service')},
            },
        ),
    ]
