# Generated by Django 4.2.30 on 2026-06-16 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masseurs', '0004_work_location_and_shift'),
        ('services', '0003_work_location_and_shift'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('name_cs', models.CharField(max_length=120, verbose_name='Name (CS)')),
                ('name_en', models.CharField(max_length=120, verbose_name='Name (EN)')),
                ('name_ru', models.CharField(max_length=120, verbose_name='Name (RU)')),
                ('address_cs', models.CharField(max_length=255, verbose_name='Address (CS)')),
                ('address_en', models.CharField(max_length=255, verbose_name='Address (EN)')),
                ('address_ru', models.CharField(max_length=255, verbose_name='Address (RU)')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Work location',
                'verbose_name_plural': 'Work locations',
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['start_time'], 'verbose_name': 'Time slot', 'verbose_name_plural': 'Time slots'},
        ),
        migrations.AddField(
            model_name='timeslot',
            name='shift_type',
            field=models.CharField(blank=True, choices=[('day', 'Day shift'), ('night', 'Night shift')], max_length=8, verbose_name='Shift type'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='is_booked',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is booked'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='masseuse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='masseurs.masseuse', verbose_name='Masseuse'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.massagetype', verbose_name='Massage type'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.DateTimeField(db_index=True, verbose_name='Start time'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='schedule.worklocation', verbose_name='Location'),
        ),
    ]
